### ISSUE TITLE
Restust - relicense repository?

### ISSUE THREAD

**Issue by kphillisjr** [Photosounder/rouziclib#1]
I saw the message about this git repository on [issue number 203](https://github.com/nothings/stb/issues/203#issuecomment-377718637) of the [Nothings STB git repository](https://github.com/nothings/stb/). This issue is a request to change the license (from  GNU General Public License v2.0 ) to a license that is easier for Developers to use.

1. Use the License system found on Sean Barret's repository mentioned above. This is a dual-license system of MIT License([Wikipedia link](https://en.wikipedia.org/wiki/MIT_License)) / [Unlicense ([Wikipedia Link](https://en.wikipedia.org/wiki/Unlicense)).
2. Use zlib License ([Wikipedia Link](https://en.wikipedia.org/wiki/Zlib_License)) like various other projects use ( like libSDL, libPNG, zlib, etc)
3. Artistic License 2.0 ([Wikipedia Link](https://en.wikipedia.org/wiki/Artistic_License))
4. Apache License 2.0 ([Wikipedia Link](https://en.wikipedia.org/wiki/Apache_License))

**Comment by Photosounder** [comment]
I originally picked GPLv2 so that I wouldn't have to worry about competition taking all my awesome code and running with it, however given my desire to let the code be adapted I should probably change it. I guess Apache should do.

Edit: Done.
