### ISSUE TITLE
sscanf safe checks

### ISSUE THREAD

**Issue by B1Z0N** [Photosounder/rouziclib#3]
There are no return value checks on `sscanf` calls. For example [here](https://github.com/Photosounder/rouziclib/blob/683c972d6508d1179bafb1c6611888ab73da5db1/rouziclib/vector_type/make_font.c#L123) and in many other different places across the codebase.

**Comment by Photosounder** [comment]
I know, you don't need the return value of `sscanf` if you use `%n` at the end on an `int` that is set to 0, because that `int` will only be set to something other than 0 if everything that precedes was parsed as expected.
